name: Close related issues

on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - main
      - release/1
      - release/2
      - release/3

jobs:
  closeIssueOnPrMergeTrigger:

    runs-on: ubuntu-latest

    steps:
      - name: Closes issues related to a merged pull request.
        uses: ldez/gha-mjolnir@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}